name: Build Application

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name AutomatedCostModelling --add-data "backend;backend" --add-data "frontend;frontend" --add-data "REDISTRIBUTED MY26 Deswik Dump Summary Mine Physicals 22 August 2025.xlsx;." main.py
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AutomatedCostModelling
        path: dist/AutomatedCostModelling.exe